name: edustore
description: Marketplace éducative Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.9
  file_picker: 8.0.7
  flutter_dotenv: ^5.2.1
 # ✅ Firebase packages compatibles entre eux
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  google_sign_in: ^6.1.5
  http_parser: ^4.0.2
  path: ^1.9.0
  path_provider: ^2.1.1
  mime: ^1.0.4

 
 
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env.example

